//@base_url = http://localhost:8000
@base_url = http://localhost:3000/api

### Get payment options
GET {{base_url}}/payments/options
content-type: application/json

### Get payment 1
GET {{base_url}}/user/111/payments/1
content-type: application/json

### Delete payment 1
DELETE {{base_url}}/user/111/payments/4
content-type: application/json

### Get all payments from one user
GET {{base_url}}/user/111/payments

### Create payment
POST {{base_url}}/user/111/payments
content-type: application/json

{
    "optionId": "opt4"
}

### Execute downpayment
PATCH {{base_url}}/user/111/payments/1/execute/downpayment
content-type: application/json

{
    
}