//@base_url = http://localhost:8000
@base_url = http://localhost:3000/api

###
GET {{base_url}}/payments/options
content-type: application/json

###
GET {{base_url}}/user/111/payments/999
content-type: application/json

###
DELETE {{base_url}}/user/111/payments/999
content-type: application/json


###
POST {{base_url}}/user/111/payments/create
content-type: application/json

{
    "optionId": "opt4"
}

###
PATCH {{base_url}}/user/111/payments/999/execute/downpayment
content-type: application/json

{
    
}