import type { Metadata } from "next";
import { nunito, nunitoBold } from "../utils/fonts";
import "./globals.css";
import Logo from "@/components/Logo";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito} ${nunitoBold} text-textPrimary`}>
        <Logo />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
