import Footer from "@/components/Footer";
import type { Metadata } from "next";
import PaymentDetailsPage from "./component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PaymentDetailsPage>{children}</PaymentDetailsPage>
    </>
  );
}
