import type { Metadata } from "next";
import PaymentDetailsPage from "./component";
import PaymentContextProvider from "@/contexts/global-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <PaymentContextProvider>
      <PaymentDetailsPage>{children}</PaymentDetailsPage>
      </PaymentContextProvider>
    </>
  );
}
